//! Ahead-of-time project transpilation.
//!
//! Walks the module graph from a project's entry, compiles each
//! `.tsx`/`.ts`/`.jsx` module to JavaScript, collects imported CSS, and produces
//! a single Rust source file exposing `modules() -> Vec<solite::VirtualSourceFile>`.
//! The host loads the result via `solite::Instance::new_from_virtual_files` — no
//! source directory shipped, no compilation at launch (the host may even be built
//! without the `jsx-compiler` feature, since every emitted module is plain `.js`).
//!
//! This powers the `solite-build bundle` CLI, and is also designed to be called from a
//! Cargo build script:
//!
//! ```no_run
//! // build.rs
//! fn main() {
//!     let out = std::path::Path::new(&std::env::var("OUT_DIR").unwrap()).join("app.rs");
//!     let generated = solite_build::bundle::bundle_to_file("ui", &out).expect("solite-build bundle");
//!     // Re-run when any source file changes.
//!     for src in &generated.sources {
//!         println!("cargo:rerun-if-changed={}", src.display());
//!     }
//! }
//! ```
//!
//! ```ignore
//! // src/main.rs
//! mod app { include!(concat!(env!("OUT_DIR"), "/app.rs")); }
//! // ... let (instance, events) = solite::Instance::new_from_virtual_files(config, app::modules())?;
//! ```
//!
//! Not for security or privacy: input paths and file contents are read verbatim.

use std::collections::{BTreeMap, HashSet, VecDeque};
use std::error::Error;
use std::fmt;
use std::io;
use std::path::{Path, PathBuf};

use relative_path::{RelativePath, RelativePathBuf};

use crate::compiler::{CompileError, compile_component_source, map_module_specifiers};

// Mirrors `src/js/mod.rs` so build-time resolution matches the runtime's lazy
// resolver. ENTRYPOINTS is searched in order; MODULE_EXTS is the extension
// search order for extensionless relative imports (the runtime tries `.js`
// first — see MODULE_PATTERNS).
const ENTRYPOINTS: [&str; 10] = [
    "index.tsx",
    "app.tsx",
    "index.jsx",
    "app.jsx",
    "index.ts",
    "app.ts",
    "index.js",
    "app.js",
    "index.mjs",
    "app.mjs",
];
const MODULE_EXTS: [&str; 5] = ["js", "mjs", "jsx", "ts", "tsx"];

/// A single emitted module: a virtual path (`.js` or `.css`) and its contents.
#[derive(Debug, Clone)]
pub struct Module {
    pub path: String,
    pub source: String,
}

/// The result of transpiling a project graph.
#[derive(Debug, Clone)]
pub struct Generated {
    /// Entry module key the runtime resolves and mounts first (e.g. `index.js`).
    pub entry: String,
    /// Emitted modules, ordered by path for deterministic output.
    pub modules: Vec<Module>,
    /// Absolute paths of every source file read, for `cargo:rerun-if-changed`.
    pub sources: Vec<PathBuf>,
}

impl Generated {
    /// Render the generated Rust source: a `modules()` function plus an `ENTRY`
    /// constant, suitable for `include!` from a Cargo `OUT_DIR`.
    pub fn to_rust_source(&self) -> String {
        let mut out = String::new();
        out.push_str("// @generated by `solite-build bundle` — do not edit.\n//\n");
        out.push_str("// Mount with:\n");
        out.push_str("//   let (instance, events) =\n");
        out.push_str("//       solite::Instance::new_from_virtual_files(config, modules())?;\n\n");

        out.push_str("/// Entry module the runtime resolves and mounts first.\n");
        out.push_str(&format!("pub const ENTRY: &str = {:?};\n\n", self.entry));

        out.push_str("/// All transpiled JS modules and raw CSS for this app, ready to mount via\n");
        out.push_str("/// [`solite::Instance::new_from_virtual_files`].\n");
        out.push_str("pub fn modules() -> Vec<solite::VirtualSourceFile> {\n    vec![\n");
        for module in &self.modules {
            let (open, close) = raw_string_delims(&module.source);
            out.push_str("        solite::VirtualSourceFile {\n");
            out.push_str(&format!("            path: {:?}.to_string(),\n", module.path));
            out.push_str(&format!(
                "            source: {open}{}{close}.to_string(),\n",
                module.source
            ));
            out.push_str("        },\n");
        }
        out.push_str("    ]\n}\n");
        out
    }
}

/// Error raised while transpiling a project.
#[derive(Debug)]
pub enum BundleError {
    NoEntry(PathBuf),
    Read(PathBuf, io::Error),
    Write(PathBuf, io::Error),
    Compile(CompileError),
    Unresolved { importer: String, specifier: String },
}

impl fmt::Display for BundleError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::NoEntry(dir) => write!(
                f,
                "no entry module found in {} (looked for {})",
                dir.display(),
                ENTRYPOINTS.join(", ")
            ),
            Self::Read(path, err) => write!(f, "reading {}: {err}", path.display()),
            Self::Write(path, err) => write!(f, "writing {}: {err}", path.display()),
            Self::Compile(err) => write!(f, "compiling: {err}"),
            Self::Unresolved {
                importer,
                specifier,
            } => write!(
                f,
                "{importer} imports {specifier:?}, which could not be resolved"
            ),
        }
    }
}

impl Error for BundleError {}

impl From<CompileError> for BundleError {
    fn from(value: CompileError) -> Self {
        Self::Compile(value)
    }
}

/// Transpile the project rooted at `src_dir` and return the generated modules.
///
/// Does not touch the filesystem beyond reading the project sources; use
/// [`Generated::to_rust_source`] to render the output, or [`bundle_to_file`] to
/// write it directly.
pub fn generate(src_dir: &Path) -> Result<Generated, BundleError> {
    let entry = find_entry(src_dir)?;

    // Output keyed by emitted path (`.js`/`.css`) for deterministic ordering.
    let mut modules: BTreeMap<String, String> = BTreeMap::new();
    let mut sources: Vec<PathBuf> = Vec::new();
    let mut visited: HashSet<String> = HashSet::new();
    let mut queue: VecDeque<RelativePathBuf> = VecDeque::new();
    queue.push_back(entry.clone());

    while let Some(rel) = queue.pop_front() {
        if !visited.insert(rel.as_str().to_string()) {
            continue;
        }
        let abs = rel.to_path(src_dir);
        sources.push(abs.clone());

        // CSS is shipped verbatim; the runtime's virtual loader self-registers
        // it as a stylesheet on import.
        if rel.extension() == Some("css") {
            let css = std::fs::read_to_string(&abs).map_err(|err| BundleError::Read(abs, err))?;
            modules.insert(rel.as_str().to_string(), css);
            continue;
        }

        let source =
            std::fs::read_to_string(&abs).map_err(|err| BundleError::Read(abs.clone(), err))?;
        let compiled = compile_component_source(&abs, &source)?;
        // Rewrite explicit source-extension imports to the `.js` keys we emit;
        // extensionless and `.css` specifiers already resolve correctly.
        let (rewritten, specifiers) = map_module_specifiers(&compiled, rewrite_extension)?;

        modules.insert(rel.with_extension("js").as_str().to_string(), rewritten);

        for specifier in specifiers {
            if !specifier.starts_with('.') {
                // Bare specifier — `solite-runtime` / `solid-js` builtins.
                continue;
            }
            queue.push_back(resolve_relative(&rel, &specifier, src_dir)?);
        }
    }

    Ok(Generated {
        entry: entry.with_extension("js").as_str().to_string(),
        modules: modules
            .into_iter()
            .map(|(path, source)| Module { path, source })
            .collect(),
        sources,
    })
}

/// Transpile the project rooted at `src_dir` and write the generated Rust source
/// to `out`, returning the [`Generated`] result (whose `sources` are useful for
/// `cargo:rerun-if-changed`).
pub fn bundle_to_file(src_dir: impl AsRef<Path>, out: impl AsRef<Path>) -> Result<Generated, BundleError> {
    let generated = generate(src_dir.as_ref())?;
    let out = out.as_ref();
    std::fs::write(out, generated.to_rust_source())
        .map_err(|err| BundleError::Write(out.to_path_buf(), err))?;
    Ok(generated)
}

fn find_entry(src_dir: &Path) -> Result<RelativePathBuf, BundleError> {
    ENTRYPOINTS
        .iter()
        .find(|name| src_dir.join(name).is_file())
        .map(|name| RelativePathBuf::from(*name))
        .ok_or_else(|| BundleError::NoEntry(src_dir.to_path_buf()))
}

/// Rewrite a relative import that carries a JS source extension to `.js`. Leaves
/// extensionless imports (resolved `.js`-first at runtime), `.css`, and bare
/// specifiers untouched.
fn rewrite_extension(specifier: &str) -> Option<String> {
    if !specifier.starts_with('.') {
        return None;
    }
    for ext in ["tsx", "ts", "jsx", "mjs"] {
        if let Some(stem) = specifier.strip_suffix(&format!(".{ext}")) {
            return Some(format!("{stem}.js"));
        }
    }
    None
}

/// Resolve a relative specifier against the importer's directory to a real
/// source file (mirrors the runtime's `resolve_candidate`).
fn resolve_relative(
    importer: &RelativePath,
    specifier: &str,
    src_dir: &Path,
) -> Result<RelativePathBuf, BundleError> {
    let joined = match importer.parent() {
        Some(dir) => dir.join_normalized(specifier),
        None => RelativePathBuf::from(specifier),
    };

    let unresolved = || BundleError::Unresolved {
        importer: importer.as_str().to_string(),
        specifier: specifier.to_string(),
    };

    if joined.extension().is_some() {
        return joined
            .to_path(src_dir)
            .is_file()
            .then_some(joined)
            .ok_or_else(unresolved);
    }

    MODULE_EXTS
        .iter()
        .map(|ext| joined.with_extension(ext))
        .find(|candidate| candidate.to_path(src_dir).is_file())
        .ok_or_else(unresolved)
}

/// Pick raw-string delimiters (`r#"…"#`) with enough `#`s that `source` cannot
/// terminate the literal early.
fn raw_string_delims(source: &str) -> (String, String) {
    let bytes = source.as_bytes();
    let mut needed = 1usize;
    let mut i = 0;
    while i < bytes.len() {
        if bytes[i] == b'"' {
            let mut hashes = 0;
            let mut j = i + 1;
            while j < bytes.len() && bytes[j] == b'#' {
                hashes += 1;
                j += 1;
            }
            needed = needed.max(hashes + 1);
            i = j;
        } else {
            i += 1;
        }
    }
    let hs = "#".repeat(needed);
    (format!("r{hs}\""), format!("\"{hs}"))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn rewrite_extension_swaps_source_extensions_only() {
        assert_eq!(rewrite_extension("./foo.tsx").as_deref(), Some("./foo.js"));
        assert_eq!(rewrite_extension("../a/b.ts").as_deref(), Some("../a/b.js"));
        assert_eq!(rewrite_extension("./foo.jsx").as_deref(), Some("./foo.js"));
        assert_eq!(rewrite_extension("./foo"), None); // extensionless: resolves .js-first
        assert_eq!(rewrite_extension("./styles.css"), None);
        assert_eq!(rewrite_extension("solite-runtime"), None);
    }

    #[test]
    fn raw_string_delims_escape_embedded_terminators() {
        let (open, close) = raw_string_delims("plain");
        assert_eq!((open.as_str(), close.as_str()), ("r#\"", "\"#"));
        let (open, close) = raw_string_delims("a\"#b");
        assert_eq!((open.as_str(), close.as_str()), ("r##\"", "\"##"));
    }

    #[test]
    fn generate_walks_graph_and_reports_sources() {
        // Build-script-facing API: no binary involved.
        let dir = std::env::temp_dir().join(format!("solite-build-api-{}", std::process::id()));
        let _ = std::fs::remove_dir_all(&dir);
        std::fs::create_dir_all(&dir).unwrap();
        std::fs::write(
            dir.join("index.tsx"),
            "import { render } from \"solite-runtime\";\n\
             import \"./styles.css\";\n\
             function App() { return <div>hi</div>; }\n\
             render(() => App(), __SOL_ROOT__);\n",
        )
        .unwrap();
        std::fs::write(dir.join("styles.css"), ".app { color: red; }\n").unwrap();

        let generated = generate(&dir).expect("generate");

        assert_eq!(generated.entry, "index.js");
        let paths: Vec<&str> = generated.modules.iter().map(|m| m.path.as_str()).collect();
        assert!(paths.contains(&"index.js"), "missing index.js: {paths:?}");
        assert!(paths.contains(&"styles.css"), "missing styles.css: {paths:?}");
        // sources are the on-disk files read — usable for cargo:rerun-if-changed.
        assert!(generated.sources.iter().any(|p| p.ends_with("index.tsx")));
        assert!(generated.sources.iter().any(|p| p.ends_with("styles.css")));
        // Rendered Rust output exposes the expected API surface.
        let rs = generated.to_rust_source();
        assert!(rs.contains("pub fn modules() -> Vec<solite::VirtualSourceFile>"));
        assert!(rs.contains("pub const ENTRY: &str = \"index.js\";"));

        let _ = std::fs::remove_dir_all(&dir);
    }
}
